// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet_Content_Type int32

const (
	Packet_Content_DATA Packet_Content_Type = 0
	Packet_Content_FILE Packet_Content_Type = 1
	Packet_Content_TEXT Packet_Content_Type = 2
	Packet_Content_MSG  Packet_Content_Type = 3
)

var Packet_Content_Type_name = map[int32]string{
	0: "DATA",
	1: "FILE",
	2: "TEXT",
	3: "MSG",
}

var Packet_Content_Type_value = map[string]int32{
	"DATA": 0,
	"FILE": 1,
	"TEXT": 2,
	"MSG":  3,
}

func (x Packet_Content_Type) Enum() *Packet_Content_Type {
	p := new(Packet_Content_Type)
	*p = x
	return p
}

func (x Packet_Content_Type) String() string {
	return proto.EnumName(Packet_Content_Type_name, int32(x))
}

func (x *Packet_Content_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Packet_Content_Type_value, data, "Packet_Content_Type")
	if err != nil {
		return err
	}
	*x = Packet_Content_Type(value)
	return nil
}

func (Packet_Content_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0, 0}
}

type Packet_Content_MsgType int32

const (
	Packet_Content_DEBUG   Packet_Content_MsgType = 0
	Packet_Content_INFO    Packet_Content_MsgType = 1
	Packet_Content_WARNING Packet_Content_MsgType = 2
	Packet_Content_ERROR   Packet_Content_MsgType = 3
)

var Packet_Content_MsgType_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
}

var Packet_Content_MsgType_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
}

func (x Packet_Content_MsgType) Enum() *Packet_Content_MsgType {
	p := new(Packet_Content_MsgType)
	*p = x
	return p
}

func (x Packet_Content_MsgType) String() string {
	return proto.EnumName(Packet_Content_MsgType_name, int32(x))
}

func (x *Packet_Content_MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Packet_Content_MsgType_value, data, "Packet_Content_MsgType")
	if err != nil {
		return err
	}
	*x = Packet_Content_MsgType(value)
	return nil
}

func (Packet_Content_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0, 1}
}

type Packet struct {
	Module               *string         `protobuf:"bytes,1,req,name=module" json:"module,omitempty"`
	Source               *string         `protobuf:"bytes,2,req,name=source" json:"source,omitempty"`
	Destination          *string         `protobuf:"bytes,3,req,name=destination" json:"destination,omitempty"`
	Timestamp            *int64          `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	Content              *Packet_Content `protobuf:"bytes,5,req,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func (m *Packet) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Packet) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *Packet) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Packet) GetContent() *Packet_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type Packet_Content struct {
	Type                 *Packet_Content_Type    `protobuf:"varint,1,req,name=type,enum=protocol.Packet_Content_Type,def=0" json:"type,omitempty"`
	Data                 []byte                  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	Name                 *string                 `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Part                 *Packet_Content_Part    `protobuf:"bytes,4,opt,name=part" json:"part,omitempty"`
	Uniq                 *string                 `protobuf:"bytes,5,opt,name=uniq" json:"uniq,omitempty"`
	MsgType              *Packet_Content_MsgType `protobuf:"varint,6,opt,name=msg_type,json=msgType,enum=protocol.Packet_Content_MsgType" json:"msg_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Packet_Content) Reset()         { *m = Packet_Content{} }
func (m *Packet_Content) String() string { return proto.CompactTextString(m) }
func (*Packet_Content) ProtoMessage()    {}
func (*Packet_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

func (m *Packet_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Content.Unmarshal(m, b)
}
func (m *Packet_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Content.Marshal(b, m, deterministic)
}
func (m *Packet_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Content.Merge(m, src)
}
func (m *Packet_Content) XXX_Size() int {
	return xxx_messageInfo_Packet_Content.Size(m)
}
func (m *Packet_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Content proto.InternalMessageInfo

const Default_Packet_Content_Type Packet_Content_Type = Packet_Content_DATA

func (m *Packet_Content) GetType() Packet_Content_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Packet_Content_Type
}

func (m *Packet_Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Packet_Content) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Packet_Content) GetPart() *Packet_Content_Part {
	if m != nil {
		return m.Part
	}
	return nil
}

func (m *Packet_Content) GetUniq() string {
	if m != nil && m.Uniq != nil {
		return *m.Uniq
	}
	return ""
}

func (m *Packet_Content) GetMsgType() Packet_Content_MsgType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return Packet_Content_DEBUG
}

type Packet_Content_Part struct {
	Number               *int32   `protobuf:"varint,1,req,name=number" json:"number,omitempty"`
	Total                *int32   `protobuf:"varint,2,req,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet_Content_Part) Reset()         { *m = Packet_Content_Part{} }
func (m *Packet_Content_Part) String() string { return proto.CompactTextString(m) }
func (*Packet_Content_Part) ProtoMessage()    {}
func (*Packet_Content_Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0, 0}
}

func (m *Packet_Content_Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet_Content_Part.Unmarshal(m, b)
}
func (m *Packet_Content_Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet_Content_Part.Marshal(b, m, deterministic)
}
func (m *Packet_Content_Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet_Content_Part.Merge(m, src)
}
func (m *Packet_Content_Part) XXX_Size() int {
	return xxx_messageInfo_Packet_Content_Part.Size(m)
}
func (m *Packet_Content_Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet_Content_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Packet_Content_Part proto.InternalMessageInfo

func (m *Packet_Content_Part) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *Packet_Content_Part) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.Packet_Content_Type", Packet_Content_Type_name, Packet_Content_Type_value)
	proto.RegisterEnum("protocol.Packet_Content_MsgType", Packet_Content_MsgType_name, Packet_Content_MsgType_value)
	proto.RegisterType((*Packet)(nil), "protocol.Packet")
	proto.RegisterType((*Packet_Content)(nil), "protocol.Packet.Content")
	proto.RegisterType((*Packet_Content_Part)(nil), "protocol.Packet.Content.Part")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x5f, 0xeb, 0xd3, 0x30,
	0x14, 0xb5, 0x6d, 0xba, 0xae, 0xb7, 0x32, 0x4a, 0x10, 0x09, 0x43, 0x21, 0xec, 0xa9, 0x2f, 0x16,
	0x2c, 0xa2, 0xa0, 0x4f, 0xd3, 0x75, 0x63, 0xe0, 0xfe, 0x10, 0x2b, 0xfa, 0x26, 0xb1, 0x0b, 0xa3,
	0xb8, 0x36, 0xb5, 0x4d, 0x1f, 0xf6, 0x19, 0xfc, 0x46, 0x7e, 0x3a, 0x49, 0xd2, 0xa9, 0x2f, 0xfb,
	0xbd, 0x9d, 0x73, 0x72, 0xef, 0xb9, 0xe7, 0x10, 0x98, 0xb5, 0x9d, 0x54, 0xb2, 0x94, 0x97, 0xd4,
	0x00, 0x3c, 0xbd, 0xf1, 0xc5, 0x6f, 0x04, 0x93, 0x23, 0x2f, 0x7f, 0x08, 0x85, 0x9f, 0xc2, 0xa4,
	0x96, 0xa7, 0xe1, 0x22, 0x88, 0x43, 0xdd, 0x24, 0x64, 0x23, 0xd3, 0x7a, 0x2f, 0x87, 0xae, 0x14,
	0xc4, 0xb5, 0xba, 0x65, 0x98, 0x42, 0x74, 0x12, 0xbd, 0xaa, 0x1a, 0xae, 0x2a, 0xd9, 0x10, 0xcf,
	0x3c, 0xfe, 0x2f, 0xe1, 0x67, 0x10, 0xaa, 0xaa, 0x16, 0xbd, 0xe2, 0x75, 0x4b, 0x10, 0x75, 0x13,
	0x8f, 0xfd, 0x13, 0x70, 0x06, 0x41, 0x29, 0x1b, 0x25, 0x1a, 0x45, 0x7c, 0xea, 0x26, 0x51, 0x46,
	0xd2, 0xbf, 0x31, 0x6d, 0xa4, 0xf4, 0x83, 0x7d, 0x67, 0xb7, 0xc1, 0xf9, 0x2f, 0x0f, 0x82, 0x51,
	0xc4, 0x6f, 0x00, 0xa9, 0x6b, 0x6b, 0xd3, 0xce, 0xb2, 0xe7, 0xf7, 0x96, 0xd3, 0xe2, 0xda, 0x8a,
	0xb7, 0x68, 0xb5, 0x2c, 0x96, 0xcc, 0x2c, 0x60, 0x0c, 0xe8, 0xc4, 0x15, 0x37, 0x75, 0x1e, 0x33,
	0x83, 0xb5, 0xd6, 0xf0, 0x5a, 0x10, 0x8f, 0x3a, 0x49, 0xc8, 0x0c, 0xc6, 0x2f, 0x01, 0xb5, 0xbc,
	0x53, 0x04, 0x51, 0x27, 0x89, 0x1e, 0x38, 0x70, 0xe4, 0x9d, 0x62, 0x66, 0x54, 0xdb, 0x0c, 0x4d,
	0xf5, 0x93, 0xf8, 0xd6, 0x46, 0x63, 0xfc, 0x0e, 0xa6, 0x75, 0x7f, 0xfe, 0x66, 0xb2, 0x4e, 0xa8,
	0x93, 0xcc, 0x32, 0x7a, 0xd7, 0x6a, 0xd7, 0x9f, 0x75, 0x5c, 0x16, 0xd4, 0x16, 0xcc, 0x5f, 0x01,
	0xd2, 0xf6, 0xfa, 0x13, 0x9a, 0xa1, 0xfe, 0x2e, 0x3a, 0x53, 0xd7, 0x67, 0x23, 0xc3, 0x4f, 0xc0,
	0x57, 0x52, 0xf1, 0x8b, 0x29, 0xe3, 0x33, 0x4b, 0x16, 0x2f, 0x00, 0xe9, 0x6d, 0x3c, 0x05, 0xd3,
	0x3b, 0x7e, 0xa4, 0xd1, 0x7a, 0xfb, 0x31, 0x8f, 0x1d, 0x8d, 0x8a, 0xfc, 0x6b, 0x11, 0xbb, 0x38,
	0x00, 0x6f, 0xf7, 0x69, 0x13, 0x7b, 0x8b, 0xd7, 0x10, 0x8c, 0x87, 0x71, 0x08, 0xfe, 0x2a, 0x7f,
	0xff, 0x79, 0x63, 0x57, 0xb6, 0xfb, 0xf5, 0x21, 0x76, 0x70, 0x04, 0xc1, 0x97, 0x25, 0xdb, 0x6f,
	0xf7, 0x9b, 0xd8, 0xd5, 0x13, 0x39, 0x63, 0x07, 0x16, 0x7b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xff, 0xe4, 0xcc, 0x57, 0x02, 0x00, 0x00,
}
