// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_UNKNOWN                 Message_Type = 0
	Message_GET_INFORMATION         Message_Type = 1
	Message_INFORMATION_RESULT      Message_Type = 2
	Message_GET_STATUS_MODULES      Message_Type = 3
	Message_STATUS_MODULES_RESULT   Message_Type = 4
	Message_START_MODULES           Message_Type = 5
	Message_STOP_MODULES            Message_Type = 6
	Message_UPDATE_MODULES          Message_Type = 7
	Message_UPDATE_CONFIG_MODULES   Message_Type = 8
	Message_AUTHENTICATION_REQUEST  Message_Type = 9
	Message_AUTHENTICATION_RESPONSE Message_Type = 10
)

var Message_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GET_INFORMATION",
	2:  "INFORMATION_RESULT",
	3:  "GET_STATUS_MODULES",
	4:  "STATUS_MODULES_RESULT",
	5:  "START_MODULES",
	6:  "STOP_MODULES",
	7:  "UPDATE_MODULES",
	8:  "UPDATE_CONFIG_MODULES",
	9:  "AUTHENTICATION_REQUEST",
	10: "AUTHENTICATION_RESPONSE",
}

var Message_Type_value = map[string]int32{
	"UNKNOWN":                 0,
	"GET_INFORMATION":         1,
	"INFORMATION_RESULT":      2,
	"GET_STATUS_MODULES":      3,
	"STATUS_MODULES_RESULT":   4,
	"START_MODULES":           5,
	"STOP_MODULES":            6,
	"UPDATE_MODULES":          7,
	"UPDATE_CONFIG_MODULES":   8,
	"AUTHENTICATION_REQUEST":  9,
	"AUTHENTICATION_RESPONSE": 10,
}

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (x *Message_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_Type_value, data, "Message_Type")
	if err != nil {
		return err
	}
	*x = Message_Type(value)
	return nil
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0, 0}
}

type ModuleStatus_Status int32

const (
	ModuleStatus_UNKNOWN ModuleStatus_Status = 0
	ModuleStatus_LOADED  ModuleStatus_Status = 1
	ModuleStatus_RUNNING ModuleStatus_Status = 2
	ModuleStatus_STOPPED ModuleStatus_Status = 3
	ModuleStatus_FREED   ModuleStatus_Status = 4
)

var ModuleStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOADED",
	2: "RUNNING",
	3: "STOPPED",
	4: "FREED",
}

var ModuleStatus_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"LOADED":  1,
	"RUNNING": 2,
	"STOPPED": 3,
	"FREED":   4,
}

func (x ModuleStatus_Status) Enum() *ModuleStatus_Status {
	p := new(ModuleStatus_Status)
	*p = x
	return p
}

func (x ModuleStatus_Status) String() string {
	return proto.EnumName(ModuleStatus_Status_name, int32(x))
}

func (x *ModuleStatus_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ModuleStatus_Status_value, data, "ModuleStatus_Status")
	if err != nil {
		return err
	}
	*x = ModuleStatus_Status(value)
	return nil
}

func (ModuleStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7, 0}
}

// Common message protocol
type Message struct {
	Type                 *Message_Type `protobuf:"varint,1,req,name=type,enum=agent.Message_Type,def=0" json:"type,omitempty"`
	Payload              []byte        `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

const Default_Message_Type Message_Type = Message_UNKNOWN

func (m *Message) GetType() Message_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Message_Type
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Struct of authentication request for handshake
// atoken means agent token which is last stored value on agent side
type AuthenticationRequest struct {
	Timestamp            *int64   `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	Atoken               *string  `protobuf:"bytes,2,req,name=atoken" json:"atoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *AuthenticationRequest) GetAtoken() string {
	if m != nil && m.Atoken != nil {
		return *m.Atoken
	}
	return ""
}

// Struct of authentication request for handshake
// atoken means agent token which will use for send API function from server
// stoken means server token which will use for send API function from agent
type AuthenticationResponse struct {
	Atoken               *string  `protobuf:"bytes,1,req,name=atoken" json:"atoken,omitempty"`
	Stoken               *string  `protobuf:"bytes,2,req,name=stoken" json:"stoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResponse) Reset()         { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()    {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *AuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResponse.Unmarshal(m, b)
}
func (m *AuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResponse.Merge(m, src)
}
func (m *AuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResponse.Size(m)
}
func (m *AuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResponse proto.InternalMessageInfo

func (m *AuthenticationResponse) GetAtoken() string {
	if m != nil && m.Atoken != nil {
		return *m.Atoken
	}
	return ""
}

func (m *AuthenticationResponse) GetStoken() string {
	if m != nil && m.Stoken != nil {
		return *m.Stoken
	}
	return ""
}

// Config is structure that contains information about module
type Config struct {
	AgentId              *string      `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Os                   []*Config_OS `protobuf:"bytes,2,rep,name=os" json:"os,omitempty"`
	Name                 *string      `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Version              *string      `protobuf:"bytes,4,req,name=version" json:"version,omitempty"`
	Events               []string     `protobuf:"bytes,5,rep,name=events" json:"events,omitempty"`
	LastUpdate           *string      `protobuf:"bytes,6,req,name=last_update,json=lastUpdate" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAgentId() string {
	if m != nil && m.AgentId != nil {
		return *m.AgentId
	}
	return ""
}

func (m *Config) GetOs() []*Config_OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *Config) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Config) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Config) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Config) GetLastUpdate() string {
	if m != nil && m.LastUpdate != nil {
		return *m.LastUpdate
	}
	return ""
}

type Config_OS struct {
	Type                 *string  `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Arch                 []string `protobuf:"bytes,2,rep,name=arch" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_OS) Reset()         { *m = Config_OS{} }
func (m *Config_OS) String() string { return proto.CompactTextString(m) }
func (*Config_OS) ProtoMessage()    {}
func (*Config_OS) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3, 0}
}

func (m *Config_OS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_OS.Unmarshal(m, b)
}
func (m *Config_OS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_OS.Marshal(b, m, deterministic)
}
func (m *Config_OS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_OS.Merge(m, src)
}
func (m *Config_OS) XXX_Size() int {
	return xxx_messageInfo_Config_OS.Size(m)
}
func (m *Config_OS) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_OS.DiscardUnknown(m)
}

var xxx_messageInfo_Config_OS proto.InternalMessageInfo

func (m *Config_OS) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Config_OS) GetArch() []string {
	if m != nil {
		return m.Arch
	}
	return nil
}

// ConfigItem is structure that contains information about config module
type ConfigItem struct {
	DefaultConfig        *string  `protobuf:"bytes,1,req,name=default_config,json=defaultConfig" json:"default_config,omitempty"`
	ConfigSchema         *string  `protobuf:"bytes,2,req,name=config_schema,json=configSchema" json:"config_schema,omitempty"`
	CurrentConfig        *string  `protobuf:"bytes,3,req,name=current_config,json=currentConfig" json:"current_config,omitempty"`
	EventDataSchema      *string  `protobuf:"bytes,4,req,name=event_data_schema,json=eventDataSchema" json:"event_data_schema,omitempty"`
	EventConfigSchema    *string  `protobuf:"bytes,5,req,name=event_config_schema,json=eventConfigSchema" json:"event_config_schema,omitempty"`
	DefaultEventConfig   *string  `protobuf:"bytes,6,req,name=default_event_config,json=defaultEventConfig" json:"default_event_config,omitempty"`
	CurrentEventConfig   *string  `protobuf:"bytes,7,req,name=current_event_config,json=currentEventConfig" json:"current_event_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigItem) Reset()         { *m = ConfigItem{} }
func (m *ConfigItem) String() string { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()    {}
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *ConfigItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigItem.Unmarshal(m, b)
}
func (m *ConfigItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigItem.Marshal(b, m, deterministic)
}
func (m *ConfigItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigItem.Merge(m, src)
}
func (m *ConfigItem) XXX_Size() int {
	return xxx_messageInfo_ConfigItem.Size(m)
}
func (m *ConfigItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigItem proto.InternalMessageInfo

func (m *ConfigItem) GetDefaultConfig() string {
	if m != nil && m.DefaultConfig != nil {
		return *m.DefaultConfig
	}
	return ""
}

func (m *ConfigItem) GetConfigSchema() string {
	if m != nil && m.ConfigSchema != nil {
		return *m.ConfigSchema
	}
	return ""
}

func (m *ConfigItem) GetCurrentConfig() string {
	if m != nil && m.CurrentConfig != nil {
		return *m.CurrentConfig
	}
	return ""
}

func (m *ConfigItem) GetEventDataSchema() string {
	if m != nil && m.EventDataSchema != nil {
		return *m.EventDataSchema
	}
	return ""
}

func (m *ConfigItem) GetEventConfigSchema() string {
	if m != nil && m.EventConfigSchema != nil {
		return *m.EventConfigSchema
	}
	return ""
}

func (m *ConfigItem) GetDefaultEventConfig() string {
	if m != nil && m.DefaultEventConfig != nil {
		return *m.DefaultEventConfig
	}
	return ""
}

func (m *ConfigItem) GetCurrentEventConfig() string {
	if m != nil && m.CurrentEventConfig != nil {
		return *m.CurrentEventConfig
	}
	return ""
}

// Struct of module for loading into agent
type Module struct {
	Name                 *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Config               *Config        `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	Files                []*Module_File `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	Args                 []*Module_Arg  `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	ConfigItem           *ConfigItem    `protobuf:"bytes,5,opt,name=config_item,json=configItem" json:"config_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Module) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Module) GetFiles() []*Module_File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Module) GetArgs() []*Module_Arg {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Module) GetConfigItem() *ConfigItem {
	if m != nil {
		return m.ConfigItem
	}
	return nil
}

type Module_File struct {
	Path                 *string  `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module_File) Reset()         { *m = Module_File{} }
func (m *Module_File) String() string { return proto.CompactTextString(m) }
func (*Module_File) ProtoMessage()    {}
func (*Module_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5, 0}
}

func (m *Module_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module_File.Unmarshal(m, b)
}
func (m *Module_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module_File.Marshal(b, m, deterministic)
}
func (m *Module_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module_File.Merge(m, src)
}
func (m *Module_File) XXX_Size() int {
	return xxx_messageInfo_Module_File.Size(m)
}
func (m *Module_File) XXX_DiscardUnknown() {
	xxx_messageInfo_Module_File.DiscardUnknown(m)
}

var xxx_messageInfo_Module_File proto.InternalMessageInfo

func (m *Module_File) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Module_File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Module_Arg struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module_Arg) Reset()         { *m = Module_Arg{} }
func (m *Module_Arg) String() string { return proto.CompactTextString(m) }
func (*Module_Arg) ProtoMessage()    {}
func (*Module_Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5, 1}
}

func (m *Module_Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module_Arg.Unmarshal(m, b)
}
func (m *Module_Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module_Arg.Marshal(b, m, deterministic)
}
func (m *Module_Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module_Arg.Merge(m, src)
}
func (m *Module_Arg) XXX_Size() int {
	return xxx_messageInfo_Module_Arg.Size(m)
}
func (m *Module_Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Module_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Module_Arg proto.InternalMessageInfo

func (m *Module_Arg) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Module_Arg) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// Communication message for (START_MODULES | STOP_MODULES | UPDATE_MODULES) commands
type ModuleList struct {
	List                 []*Module `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModuleList) Reset()         { *m = ModuleList{} }
func (m *ModuleList) String() string { return proto.CompactTextString(m) }
func (*ModuleList) ProtoMessage()    {}
func (*ModuleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *ModuleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleList.Unmarshal(m, b)
}
func (m *ModuleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleList.Marshal(b, m, deterministic)
}
func (m *ModuleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleList.Merge(m, src)
}
func (m *ModuleList) XXX_Size() int {
	return xxx_messageInfo_ModuleList.Size(m)
}
func (m *ModuleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleList.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleList proto.InternalMessageInfo

func (m *ModuleList) GetList() []*Module {
	if m != nil {
		return m.List
	}
	return nil
}

// Struct of status module for sending to server
type ModuleStatus struct {
	Name                 *string              `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Config               *Config              `protobuf:"bytes,2,req,name=config" json:"config,omitempty"`
	ConfigItem           *ConfigItem          `protobuf:"bytes,3,req,name=config_item,json=configItem" json:"config_item,omitempty"`
	Status               *ModuleStatus_Status `protobuf:"varint,4,req,name=status,enum=agent.ModuleStatus_Status,def=0" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ModuleStatus) Reset()         { *m = ModuleStatus{} }
func (m *ModuleStatus) String() string { return proto.CompactTextString(m) }
func (*ModuleStatus) ProtoMessage()    {}
func (*ModuleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *ModuleStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleStatus.Unmarshal(m, b)
}
func (m *ModuleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleStatus.Marshal(b, m, deterministic)
}
func (m *ModuleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleStatus.Merge(m, src)
}
func (m *ModuleStatus) XXX_Size() int {
	return xxx_messageInfo_ModuleStatus.Size(m)
}
func (m *ModuleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleStatus proto.InternalMessageInfo

const Default_ModuleStatus_Status ModuleStatus_Status = ModuleStatus_UNKNOWN

func (m *ModuleStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ModuleStatus) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ModuleStatus) GetConfigItem() *ConfigItem {
	if m != nil {
		return m.ConfigItem
	}
	return nil
}

func (m *ModuleStatus) GetStatus() ModuleStatus_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_ModuleStatus_Status
}

// Communication message for STATUS_MODULES_RESULT command
type ModuleStatusList struct {
	List                 []*ModuleStatus `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ModuleStatusList) Reset()         { *m = ModuleStatusList{} }
func (m *ModuleStatusList) String() string { return proto.CompactTextString(m) }
func (*ModuleStatusList) ProtoMessage()    {}
func (*ModuleStatusList) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *ModuleStatusList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleStatusList.Unmarshal(m, b)
}
func (m *ModuleStatusList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleStatusList.Marshal(b, m, deterministic)
}
func (m *ModuleStatusList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleStatusList.Merge(m, src)
}
func (m *ModuleStatusList) XXX_Size() int {
	return xxx_messageInfo_ModuleStatusList.Size(m)
}
func (m *ModuleStatusList) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleStatusList.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleStatusList proto.InternalMessageInfo

func (m *ModuleStatusList) GetList() []*ModuleStatus {
	if m != nil {
		return m.List
	}
	return nil
}

// Communication message for INFORMATION_RESULT command
type Information struct {
	Os                   *Information_OS   `protobuf:"bytes,1,req,name=os" json:"os,omitempty"`
	User                 *Information_User `protobuf:"bytes,2,req,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Information) Reset()         { *m = Information{} }
func (m *Information) String() string { return proto.CompactTextString(m) }
func (*Information) ProtoMessage()    {}
func (*Information) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *Information) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information.Unmarshal(m, b)
}
func (m *Information) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information.Marshal(b, m, deterministic)
}
func (m *Information) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information.Merge(m, src)
}
func (m *Information) XXX_Size() int {
	return xxx_messageInfo_Information.Size(m)
}
func (m *Information) XXX_DiscardUnknown() {
	xxx_messageInfo_Information.DiscardUnknown(m)
}

var xxx_messageInfo_Information proto.InternalMessageInfo

func (m *Information) GetOs() *Information_OS {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *Information) GetUser() *Information_User {
	if m != nil {
		return m.User
	}
	return nil
}

type Information_OS struct {
	Type                 *string  `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Arch                 *string  `protobuf:"bytes,3,req,name=arch" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Information_OS) Reset()         { *m = Information_OS{} }
func (m *Information_OS) String() string { return proto.CompactTextString(m) }
func (*Information_OS) ProtoMessage()    {}
func (*Information_OS) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9, 0}
}

func (m *Information_OS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information_OS.Unmarshal(m, b)
}
func (m *Information_OS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information_OS.Marshal(b, m, deterministic)
}
func (m *Information_OS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information_OS.Merge(m, src)
}
func (m *Information_OS) XXX_Size() int {
	return xxx_messageInfo_Information_OS.Size(m)
}
func (m *Information_OS) XXX_DiscardUnknown() {
	xxx_messageInfo_Information_OS.DiscardUnknown(m)
}

var xxx_messageInfo_Information_OS proto.InternalMessageInfo

func (m *Information_OS) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Information_OS) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Information_OS) GetArch() string {
	if m != nil && m.Arch != nil {
		return *m.Arch
	}
	return ""
}

type Information_User struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Group                *string  `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Information_User) Reset()         { *m = Information_User{} }
func (m *Information_User) String() string { return proto.CompactTextString(m) }
func (*Information_User) ProtoMessage()    {}
func (*Information_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9, 1}
}

func (m *Information_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information_User.Unmarshal(m, b)
}
func (m *Information_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information_User.Marshal(b, m, deterministic)
}
func (m *Information_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information_User.Merge(m, src)
}
func (m *Information_User) XXX_Size() int {
	return xxx_messageInfo_Information_User.Size(m)
}
func (m *Information_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Information_User.DiscardUnknown(m)
}

var xxx_messageInfo_Information_User proto.InternalMessageInfo

func (m *Information_User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Information_User) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func init() {
	proto.RegisterEnum("agent.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("agent.ModuleStatus_Status", ModuleStatus_Status_name, ModuleStatus_Status_value)
	proto.RegisterType((*Message)(nil), "agent.Message")
	proto.RegisterType((*AuthenticationRequest)(nil), "agent.AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "agent.AuthenticationResponse")
	proto.RegisterType((*Config)(nil), "agent.Config")
	proto.RegisterType((*Config_OS)(nil), "agent.Config.OS")
	proto.RegisterType((*ConfigItem)(nil), "agent.ConfigItem")
	proto.RegisterType((*Module)(nil), "agent.Module")
	proto.RegisterType((*Module_File)(nil), "agent.Module.File")
	proto.RegisterType((*Module_Arg)(nil), "agent.Module.Arg")
	proto.RegisterType((*ModuleList)(nil), "agent.ModuleList")
	proto.RegisterType((*ModuleStatus)(nil), "agent.ModuleStatus")
	proto.RegisterType((*ModuleStatusList)(nil), "agent.ModuleStatusList")
	proto.RegisterType((*Information)(nil), "agent.Information")
	proto.RegisterType((*Information_OS)(nil), "agent.Information.OS")
	proto.RegisterType((*Information_User)(nil), "agent.Information.User")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0x97, 0x24, 0x9b, 0x93, 0xa6, 0xeb, 0x4e, 0x2f, 0xeb, 0x0d, 0x48, 0x04, 0xa3, 0x8a,
	0x8a, 0x4b, 0xa8, 0xf2, 0xc8, 0xbe, 0x10, 0x35, 0x4e, 0x37, 0xa2, 0xb1, 0xcb, 0xd8, 0x16, 0x8f,
	0xd1, 0x28, 0x99, 0xa6, 0xd6, 0x26, 0x76, 0xf0, 0x8c, 0x2b, 0xf5, 0x0d, 0xf1, 0x67, 0xf8, 0x19,
	0xfc, 0x0a, 0x24, 0xc4, 0xaf, 0x41, 0x73, 0x71, 0x1a, 0x2f, 0x65, 0xf7, 0xc9, 0x73, 0xbe, 0x73,
	0xbe, 0x73, 0xf7, 0x81, 0x0e, 0x59, 0xd1, 0x8c, 0x0f, 0xb6, 0x45, 0xce, 0x73, 0xd4, 0x90, 0x82,
	0xf7, 0xb7, 0x09, 0xad, 0x19, 0x65, 0x8c, 0xac, 0x28, 0xba, 0x04, 0x9b, 0x3f, 0x6e, 0xa9, 0x6b,
	0xf4, 0xcd, 0x8b, 0xc3, 0xe1, 0xf1, 0x40, 0x99, 0x6b, 0xed, 0x20, 0x7e, 0xdc, 0xd2, 0x1f, 0x5a,
	0x49, 0xf0, 0x53, 0x10, 0xfe, 0x12, 0x60, 0x69, 0x89, 0x5c, 0x68, 0x6d, 0xc9, 0xe3, 0x3a, 0x27,
	0x4b, 0xd7, 0xec, 0x1b, 0x17, 0x07, 0xb8, 0x12, 0xbd, 0xdf, 0x4c, 0xb0, 0x05, 0x03, 0x75, 0xa0,
	0xe2, 0x38, 0x9f, 0xa0, 0x63, 0x78, 0x79, 0xed, 0xc7, 0xf3, 0x69, 0x30, 0x09, 0xf1, 0x6c, 0x14,
	0x4f, 0xc3, 0xc0, 0x31, 0xd0, 0x19, 0xa0, 0x3d, 0x60, 0x8e, 0xfd, 0x28, 0xb9, 0x89, 0x1d, 0x53,
	0xe0, 0xc2, 0x38, 0x8a, 0x47, 0x71, 0x12, 0xcd, 0x67, 0xe1, 0x38, 0xb9, 0xf1, 0x23, 0xc7, 0x42,
	0xaf, 0xe1, 0xb4, 0x8e, 0x55, 0x14, 0x1b, 0x1d, 0x41, 0x37, 0x8a, 0x47, 0x38, 0xde, 0x59, 0x37,
	0x90, 0x03, 0x07, 0x51, 0x1c, 0xde, 0xee, 0x90, 0x26, 0x42, 0x70, 0x98, 0xdc, 0x8e, 0x47, 0xb1,
	0xbf, 0xc3, 0x5a, 0xc2, 0xa7, 0xc6, 0xae, 0xc2, 0x60, 0x32, 0xbd, 0xde, 0xa9, 0x5e, 0xa0, 0x1e,
	0x9c, 0x8d, 0x92, 0xf8, 0xad, 0x1f, 0xc4, 0xd3, 0xab, 0x2a, 0xc3, 0x9f, 0x13, 0x3f, 0x8a, 0x9d,
	0x36, 0xfa, 0x14, 0x5e, 0xfd, 0x47, 0x17, 0xdd, 0x86, 0x41, 0xe4, 0x3b, 0xe0, 0xcd, 0xe0, 0x74,
	0x54, 0xf2, 0x7b, 0x9a, 0xf1, 0x74, 0x41, 0x78, 0x9a, 0x67, 0x98, 0xfe, 0x5a, 0x52, 0xc6, 0xd1,
	0x67, 0xd0, 0xe6, 0xe9, 0x86, 0x32, 0x4e, 0x36, 0x5b, 0xd9, 0x6c, 0x0b, 0x3f, 0x01, 0xe8, 0x0c,
	0x9a, 0x84, 0xe7, 0xef, 0x68, 0xe6, 0x9a, 0x7d, 0xf3, 0xa2, 0x8d, 0xb5, 0xe4, 0xbd, 0x85, 0xb3,
	0xf7, 0xdd, 0xb1, 0x6d, 0x9e, 0x31, 0xba, 0xc7, 0x30, 0xf6, 0x19, 0x02, 0x67, 0x35, 0x4f, 0x4a,
	0xf2, 0xfe, 0x31, 0xa0, 0x79, 0x95, 0x67, 0x77, 0xe9, 0x0a, 0xbd, 0x86, 0x17, 0x72, 0xca, 0xf3,
	0x74, 0xa9, 0xc9, 0x2d, 0x29, 0x4f, 0x97, 0xa8, 0x0f, 0x66, 0xce, 0x5c, 0xb3, 0x6f, 0x5d, 0x74,
	0x86, 0x8e, 0xde, 0x05, 0xc5, 0x1a, 0x84, 0x11, 0x36, 0x73, 0x86, 0x10, 0xd8, 0x19, 0xd9, 0x50,
	0xd7, 0x92, 0x44, 0xf9, 0x16, 0x1b, 0xf1, 0x40, 0x0b, 0x96, 0xe6, 0x99, 0x6b, 0x2b, 0x7f, 0x5a,
	0x14, 0xd9, 0xd0, 0x07, 0x9a, 0x71, 0xe6, 0x36, 0xfa, 0x96, 0xc8, 0x46, 0x49, 0xe8, 0x73, 0xe8,
	0xac, 0x09, 0xe3, 0xf3, 0x72, 0xbb, 0x24, 0x9c, 0xba, 0x4d, 0xc9, 0x02, 0x01, 0x25, 0x12, 0xe9,
	0x7d, 0x0b, 0x66, 0x18, 0x89, 0x60, 0xbb, 0xe5, 0x6c, 0xeb, 0xf5, 0x43, 0x60, 0x93, 0x62, 0x71,
	0x2f, 0x93, 0x6c, 0x63, 0xf9, 0xf6, 0xfe, 0x34, 0x01, 0x54, 0x9a, 0x53, 0x4e, 0x37, 0xe8, 0x1c,
	0x0e, 0x97, 0xf4, 0x8e, 0x94, 0x6b, 0x3e, 0x5f, 0x48, 0x54, 0x3b, 0xe8, 0x6a, 0x54, 0xf7, 0xe1,
	0x4b, 0xe8, 0x2a, 0xf5, 0x9c, 0x2d, 0xee, 0xe9, 0x86, 0xe8, 0x8e, 0x1d, 0x28, 0x30, 0x92, 0x98,
	0xf0, 0xb5, 0x28, 0x8b, 0x42, 0xb4, 0x4b, 0xfb, 0x52, 0x95, 0x77, 0x35, 0xaa, 0x7d, 0x7d, 0x0d,
	0x47, 0xb2, 0xb4, 0xf9, 0x92, 0x70, 0x52, 0xf9, 0x53, 0xcd, 0x78, 0x29, 0x15, 0x63, 0xc2, 0x89,
	0x76, 0x39, 0x80, 0x63, 0x65, 0x5b, 0x8f, 0xde, 0x90, 0xd6, 0xca, 0xcd, 0xd5, 0x7e, 0x0a, 0x97,
	0x70, 0x52, 0x95, 0xb3, 0xcf, 0xd3, 0x5d, 0x43, 0x5a, 0xe7, 0x3f, 0xf1, 0x04, 0xa3, 0x4a, 0xba,
	0xc6, 0x68, 0x29, 0x86, 0xd6, 0xed, 0x31, 0xbc, 0x3f, 0x4c, 0x68, 0xce, 0xf2, 0x65, 0xb9, 0xa6,
	0xbb, 0x09, 0x1b, 0x7b, 0x13, 0x3e, 0x87, 0xa6, 0x76, 0x21, 0x7e, 0xf9, 0xce, 0xb0, 0x5b, 0xdb,
	0x0d, 0xac, 0x95, 0xe8, 0x02, 0x1a, 0x77, 0xe9, 0x9a, 0x32, 0xd7, 0x92, 0x1b, 0x84, 0xaa, 0x6b,
	0x22, 0x1d, 0x0f, 0x26, 0xe9, 0x9a, 0x62, 0x65, 0x80, 0xce, 0xc5, 0x14, 0x57, 0xcc, 0xb5, 0xa5,
	0xe1, 0x51, 0xdd, 0x70, 0x54, 0xac, 0xb0, 0x54, 0xa3, 0x21, 0x74, 0x74, 0x93, 0x52, 0x4e, 0x37,
	0x6e, 0x43, 0x06, 0x3f, 0xaa, 0x05, 0x17, 0x13, 0xc7, 0xb0, 0xd8, 0xbd, 0x7b, 0x03, 0xb0, 0x45,
	0x24, 0x51, 0xc7, 0x96, 0xf0, 0x7b, 0xd7, 0xe8, 0x1b, 0xa2, 0x0e, 0xf1, 0x16, 0x98, 0x18, 0x90,
	0x9c, 0xf4, 0x01, 0x96, 0xef, 0xde, 0x77, 0x60, 0x8d, 0x8a, 0x15, 0x72, 0xc0, 0x7a, 0x47, 0x1f,
	0x75, 0xd5, 0xe2, 0x89, 0x4e, 0xa0, 0xf1, 0x40, 0xd6, 0x25, 0xd5, 0xab, 0xa6, 0x04, 0xef, 0x7b,
	0x00, 0x95, 0xe6, 0x4d, 0xca, 0x38, 0xfa, 0x02, 0xec, 0x75, 0xca, 0xb8, 0x6b, 0xc8, 0x3a, 0xba,
	0xb5, 0x3a, 0xb0, 0x54, 0x79, 0xbf, 0x9b, 0x70, 0xa0, 0x80, 0x88, 0x13, 0x5e, 0xb2, 0x8f, 0x36,
	0xd8, 0xfc, 0xff, 0x06, 0xbf, 0xd7, 0x0f, 0x4b, 0xda, 0x7e, 0xb8, 0x1f, 0xe8, 0x8d, 0xb8, 0x08,
	0x22, 0xb0, 0xdc, 0xc7, 0xc3, 0x61, 0xaf, 0x96, 0xa4, 0xca, 0x69, 0xa0, 0x3e, 0x4f, 0xa7, 0x5e,
	0x53, 0xbc, 0x09, 0x34, 0x75, 0xd6, 0xb5, 0x9b, 0x0e, 0xd0, 0xbc, 0x09, 0x47, 0x63, 0x7f, 0xec,
	0x18, 0x42, 0x81, 0x93, 0x20, 0x98, 0x06, 0xd7, 0x8e, 0x29, 0x04, 0x71, 0x79, 0x6f, 0xfd, 0xb1,
	0x63, 0xa1, 0x36, 0x34, 0x26, 0xd8, 0xf7, 0xc7, 0x8e, 0xed, 0xbd, 0x01, 0x67, 0x3f, 0x9e, 0xec,
	0xdd, 0x57, 0xb5, 0xde, 0x1d, 0x3f, 0x93, 0x96, 0xee, 0xe0, 0x5f, 0x06, 0x74, 0xa6, 0xd9, 0x5d,
	0x5e, 0x6c, 0xe4, 0x0d, 0x44, 0xe7, 0xf2, 0x4a, 0x19, 0xb2, 0xf8, 0x53, 0x4d, 0xdb, 0xd3, 0x57,
	0xa7, 0xea, 0x1b, 0xb0, 0x4b, 0x46, 0x0b, 0xdd, 0xd1, 0x57, 0xcf, 0x18, 0x26, 0x8c, 0x16, 0x58,
	0x1a, 0xf5, 0x7e, 0xfc, 0xd0, 0xc1, 0x91, 0xe3, 0x32, 0xd5, 0x1e, 0xc9, 0x71, 0x55, 0x47, 0x48,
	0x5f, 0x41, 0xf1, 0xee, 0x5d, 0x82, 0x2d, 0xfc, 0x3d, 0x3b, 0xde, 0x13, 0x68, 0xac, 0x8a, 0xbc,
	0xdc, 0x6a, 0x27, 0x4a, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xbd, 0xc5, 0x58, 0x9c, 0x07,
	0x00, 0x00,
}
